<a href="https://colab.research.google.com/github/DanB1421/DATA601/blob/main/Brilliant_Hw_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## DATA 601 - Fall 2022
### Homework Assignment 3
Total points : (30 + 10)<br>
 Please provide your solutions into the cells provided after question cells. You can create new cells as needed. <br>

The focus of this homework is on the Numpy and Pandas packages but the use of Scipy package is forbidden. Also, this homework deals with [matrix inverses](https://mathworld.wolfram.com/MatrixInverse.html) for the first two questions.

<b>Question 1:</b> [<span style="color: red;">10 points</span>]<br>
(i). Create a 16x14 array, which includes random integers from 1 to 20, name this array "A". print the array A.<br>
(ii). Find all the numbers bigger than 11 and multiply them with 10, name this new array B.<br>
(iii). Replace the element on the 2nd row, 3rd column of B, with -10.<br>
(iv). Do $C = B^{T}B$, which is to multiply the B-transpose with matrix B and store in $C$.<br>
(v). Calculate the inverse of this Matrix $C^{-1}$ with the <code>numpy.linalg.inv</code> function and store in <code>Cinv</code>. Display $\|CC^{-1} - I\|_{F}$  ($\|.\|_F$ is the default norm-type for matrices in <code>np.linalg.norm</code>) where $I$ is the Identity matrix of the appropriate size

In [ ]:
#Your answers go here
import numpy as np # import numpy package

A = np.random.randint(1,21,(16,14)) # places random integers between 1-20 into a 16 x 14 matrix and stores in variable A

print(A) # displays matrix A

[[15 19  9  3 11  4 11  3 18  1  8  2  1  9]
 [10 16 14  3 11  4 12 14 10 16 19 13 18  9]
 [ 7 15  2  5 18  6 19  2 12 13  4 17 11  7]
 [17 19 12 15 16  2 13 19  6 18  9  8 13  2]
 [ 5 13 13 17 11 14 13 15 18 12 12  2  9 15]
 [ 2  8  6 10  2  6  9 19 14  8  1 12 18  9]
 [ 7 20 15 20 17 11  4 18  6  3 12  9  2  3]
 [10  1  3  5 15  5  2  9  9 16  7 12  2  2]
 [10  9 12  5  2 18  3 19  7  1 14 19  7 12]
 [18  5 19 16 10  5 18  5 20  1 16  2 13 12]
 [15 19 14 10  2  8  7 11 18 13 11 20 16  7]
 [11 12 19 19  6  7  9  3 11 20  2 10  1  2]
 [17 17  8 14  9 15 18 14  3 14  3  6 18  8]
 [20  4 17  2 13  8 13  1  9  3  3  1 10 13]
 [17  6  4 11 16  9 14 20 18  4 15  8 20  1]
 [16  7 17  2  7 15  4 18 20  1 18  7 11 17]]


In [ ]:
B = np.copy(A) # copies matrix A into variable B
for i in range(len(A)):
    for j in range(len(A[0])):
        if A[i,j]>11:
            B[i,j] = 10*A[i,j] # finds all numbers in matrix B that are greater than 11 and multiplies them by 10
print(B) # displays matrix B

[[150 190   9   3  11   4  11   3 180   1   8   2   1   9]
 [ 10 160 140   3  11   4 120 140  10 160 190 130 180   9]
 [  7 150   2   5 180   6 190   2 120 130   4 170  11   7]
 [170 190 120 150 160   2 130 190   6 180   9   8 130   2]
 [  5 130 130 170  11 140 130 150 180 120 120   2   9 150]
 [  2   8   6  10   2   6   9 190 140   8   1 120 180   9]
 [  7 200 150 200 170  11   4 180   6   3 120   9   2   3]
 [ 10   1   3   5 150   5   2   9   9 160   7 120   2   2]
 [ 10   9 120   5   2 180   3 190   7   1 140 190   7 120]
 [180   5 190 160  10   5 180   5 200   1 160   2 130 120]
 [150 190 140  10   2   8   7  11 180 130  11 200 160   7]
 [ 11 120 190 190   6   7   9   3  11 200   2  10   1   2]
 [170 170   8 140   9 150 180 140   3 140   3   6 180   8]
 [200   4 170   2 130   8 130   1   9   3   3   1  10 130]
 [170   6   4  11 160   9 140 200 180   4 150   8 200   1]
 [160   7 170   2   7 150   4 180 200   1 180   7  11 170]]


In [ ]:
B[1,2] = -10 # replaces the value in the second row and third column of matrix B with -10
print(B) # displays matrix B

[[150 190   9   3  11   4  11   3 180   1   8   2   1   9]
 [ 10 160 -10   3  11   4 120 140  10 160 190 130 180   9]
 [  7 150   2   5 180   6 190   2 120 130   4 170  11   7]
 [170 190 120 150 160   2 130 190   6 180   9   8 130   2]
 [  5 130 130 170  11 140 130 150 180 120 120   2   9 150]
 [  2   8   6  10   2   6   9 190 140   8   1 120 180   9]
 [  7 200 150 200 170  11   4 180   6   3 120   9   2   3]
 [ 10   1   3   5 150   5   2   9   9 160   7 120   2   2]
 [ 10   9 120   5   2 180   3 190   7   1 140 190   7 120]
 [180   5 190 160  10   5 180   5 200   1 160   2 130 120]
 [150 190 140  10   2   8   7  11 180 130  11 200 160   7]
 [ 11 120 190 190   6   7   9   3  11 200   2  10   1   2]
 [170 170   8 140   9 150 180 140   3 140   3   6 180   8]
 [200   4 170   2 130   8 130   1   9   3   3   1  10 130]
 [170   6   4  11 160   9 140 200 180   4 150   8 200   1]
 [160   7 170   2   7 150   4 180 200   1 180   7  11 170]]


In [ ]:
C = np.dot(B.T,B) # finds the product of matrix B's transpose and matrix B, stores in variable C

In [ ]:
Cinv = np.linalg.inv(C) # finds the inverse of matrix C and stores in variable Cinv
CCinv = np.dot(C,Cinv) # finds the product of matrix C and its inverse and stores in variable CCinv
IforC = np.identity(14) # produces the 14 x 14 identity matrix and stores in variable IforC
Cnorm = np.linalg.norm(CCinv - IforC) # finds the normal of the difference between CCinv and IforC and stores in variable Cnorm
print(Cnorm) # displays Cnorm

2.8669178182621655e-14


<b>Question 2:</b> [<span style="color: red;">10 points</span>]<br> Given a Matrix $Y$, we can partition it into $A$, $B$, $C$ and $D$; the top-left, top-right, bottom-left and bottom-right block matrices respectively.

$\displaystyle {Y = \begin{bmatrix}\mathbf {A} &\mathbf {B} \\\mathbf {C} &\mathbf {D} \end{bmatrix}}$

You need to calculate $Y^{-1}$ (the inverse) using the following block formulation.


${\displaystyle {Y^{-1} = \begin{bmatrix}\mathbf {A} &\mathbf {B} \\\mathbf {C} &\mathbf {D} \end{bmatrix}}^{-1}={\begin{bmatrix}\mathbf {A} ^{-1}+\mathbf {A} ^{-1}\mathbf {B} \left(\mathbf {D} -\mathbf {CA} ^{-1}\mathbf {B} \right)^{-1}\mathbf {CA} ^{-1}&-\mathbf {A} ^{-1}\mathbf {B} \left(\mathbf {D} -\mathbf {CA} ^{-1}\mathbf {B} \right)^{-1}\\-\left(\mathbf {D} -\mathbf {CA} ^{-1}\mathbf {B} \right)^{-1}\mathbf {CA} ^{-1}&\left(\mathbf {D} -\mathbf {CA} ^{-1}\mathbf {B} \right)^{-1}\end{bmatrix}},}$

Do not use <code>np.linalg.inv</code> function directly on $Y$ (But you are allowed to use it for on the block matrix computations shown on the RHS of the equation above). For our case, $Y$ is a $16 \times 16$ matrix and $A$, $B$, $C$ and $D$ are smaller $8 \times 8$ matrices. You need to access $Y$ from the <code>Y_matrix.npy</code> file

After you compute $Y^{-1}$ using the formulation above, Calculate the norm $\|YY^{-1} - I\|_{F}$. This value should be at least $< 10^{-8}$

In [ ]:
#Your answers go here
Y = np.load('Y_matrix.npy') # Loads Y matrix file into variable Y

Ysplit = np.vsplit(Y, 2) # Splits Y matrix into two block matrices, with th first 8 rows as the first block matrix and the last 8 rows as the second block matrix, stores in variable Ysplit

AB = Ysplit[0] # Defines the block matrix containing the first 8 rows of Y from Ysplit as AB
CD = Ysplit[1] # Defines the block matrix containing the last 8 rows of Y from Ysplit as CD

ABsplit = np.hsplit(AB, 2) # Splits AB matrix by columns into two block matrices, one containing the first 8 columns and the other containing the last 8 columns, stores in variable ABsplit
CDsplit = np.hsplit(CD, 2) # Splits CD matrix by columns into two block matrices, one containing the first 8 columns and the other containing the last 8 columns, stores in variable CDsplit

A = ABsplit[0] # defines block matrix A as the first block matrix from ABsplit (first 8 columns)

B = ABsplit[1] # defines block matrix B as the second block matrix from ABsplit (last 8 columns)

C = CDsplit[0] # defines block matrix C as the first block matrix from CDsplit (first 8 columns)

D = CDsplit[1] # defines block matrix D as the first block matrix from CDsplit (last 8 columns)

In [ ]:
Ainv = np.linalg.inv(A) # finds the inverse of block matrix A to produce Ainv matrix

Term1 = np.dot(Ainv, B) # provides the product of Ainv and B as variable Term1
Term2 = np.dot(C, Ainv) # provides the product of C and Ainv as variable Term2
Term3 = np.dot(Term2, B) # provides the product of CAinv and B as variable Term3
Term4 = D - Term3 # provides the difference between D and CAinvB as variable Term4

YinvD = np.linalg.inv(Term4) # provides the inverse of Term4 (D - CAinvB) as the D block matrix for Yinv, YinvD

Term5 = np.dot(YinvD, Term2) # provides the product of YinvD and Term2 (CAinv) as variable Term5

YinvC = np.negative(Term5) # provides the negative of Term5 (inverse[D-CAinvB]*CAinv) as the C block matrix for Yinv, YinvC

Term6 = np.dot(Term1, YinvD) # provides the product of Term1 (AinvB) and YinvD as variable Term6

YinvB = np.negative(Term6) # provides the negative of Term6 (AinvB*inverse[D-CAinvB]) as the B block matrix for Yinv, YinvB

Term7 = np.dot(Term6, Term2) # provides the product of Term6 (AinvB*inverse[D - CAinvB]) and Term2 (CAinv) as variable Term7

YinvA = Ainv + Term7 # provides the sum of Ainv and Term7 (AinvB*inverse[D - CAinvB]*CAinv) as the A block matrix fo Yinv, YinvA

Yinv = np.block([
    [YinvA, YinvB],
    [YinvC, YinvD]
])                   # creates the matrix Yinv from block matrices YinvA, YinvB, YinvC, and YinvD

In [ ]:
YYinv = np.dot(Y, Yinv) # finds the product of Y and Yinv matrices and stores in variable YYinv
IforY = np.identity(16) # produces the 16 x 16 identity matrix and stores in variable IforY
Ynorm = np.linalg.norm(YYinv - IforY) # finds the normal of the difference betweeen YYinv and IforY and stores in variable Ynorm
print(Ynorm) # displays Ynorm

3.4399043292382675e-10


<b>Question 3:</b> [<span style="color: red;">10 points</span>]:<br>
Consider a pandas dataframe called <code>student_df</code> that stores points (or marks) for Homework 1 to 4, Midterms and Finals (we are assuming all points are out of 100). The above categories would be the columns and the student names (first and last name in one string) should be the row index. View <code>example_df.png</code> for reference.<br>

You need to create the above dataframe <code>student_df</code> with random integer values between 50 and 100 for each cell in the dataframe for 10 students. The row index of the dataframe need to be created by using the <code>names</code> package, generating 10 first names and 10 last names and combining the respective first name and last name into a single string (full name). Save the dataframe as a csv file.

In [ ]:
!pip install names # Installs names package

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#Your answers go here
import pandas as pd # imports pandas package

import names # imports names package

fname = []

for i in range(10):
    firstname = names.get_first_name()
    fname.append(firstname) # produces list of 10 first names

lname = []

for i in range(10):
    lastname = names.get_last_name()
    lname.append(lastname) # produces list of 10 last names

fullname = [' '.join(name) for name in zip(fname,lname)] # joins list of first and last names into list of full names

print(fullname)

['Sandra Heller', 'James Atkinson', 'Emma Gifford', 'Kent Chambers', 'Janet Gaden', 'Edgar Girdley', 'Taylor Busi', 'Patricia Garrick', 'Christine Dyer', 'Maria Almaraz']


In [ ]:
HW1grades = []

for i in range(10):
    HW1grade = np.random.randint(50,101)
    HW1grades.append(HW1grade) # produces grades between 50 and 100 for HW1

HW2grades = []

for i in range(10):
    HW2grade = np.random.randint(50,101)
    HW2grades.append(HW2grade) # produces grades between 50 and 100 for HW2

HW3grades = []

for i in range(10):
    HW3grade = np.random.randint(50,101)
    HW3grades.append(HW3grade) # produces grades between 50 and 100 for HW3

HW4grades = []

for i in range(10):
    HW4grade = np.random.randint(50,101)
    HW4grades.append(HW4grade) # produces grades between 50 and 100 for HW4

MidtermGrades = []

for i in range(10):
    MidtermGrade = np.random.randint(50,101)
    MidtermGrades.append(MidtermGrade) # produces grades between 50 and 100 for Midterm

FinalGrades = []

for i in range(10):
    FinalGrade = np.random.randint(50,101)
    FinalGrades.append(FinalGrade) # produces grades between 50 and 100 for Final

print(HW1grades)
print(HW2grades)
print(HW3grades)
print(HW4grades)
print(MidtermGrades)
print(FinalGrades)

[91, 55, 63, 78, 64, 58, 86, 66, 75, 97]
[61, 89, 91, 63, 55, 89, 56, 88, 76, 50]
[85, 64, 50, 84, 64, 55, 80, 63, 53, 70]
[97, 89, 91, 50, 51, 89, 91, 66, 96, 70]
[57, 70, 55, 82, 87, 66, 68, 66, 100, 59]
[96, 77, 80, 89, 78, 84, 69, 63, 78, 86]


In [ ]:
HW1_dict = {fullname[i]: HW1grades[i] for i in range(len(fullname))} # produces dictionary of student names and grades for HW1
HW1 = pd.Series(HW1_dict) # produces series from dictionary of student names and grades for HW1

HW2_dict = {fullname[i]: HW2grades[i] for i in range(len(fullname))} # produces dictionary of student names and grades for HW2
HW2 = pd.Series(HW2_dict) # produces series from dictionary of student names and grades for HW2

HW3_dict = {fullname[i]: HW3grades[i] for i in range(len(fullname))} # produces dictionary of student names and grades for HW3
HW3 = pd.Series(HW3_dict) # produces series from dictionary of student names and grades for HW3

HW4_dict = {fullname[i]: HW4grades[i] for i in range(len(fullname))} # produces dictionary of student names and grades for HW4
HW4 = pd.Series(HW4_dict) # produces series from dictionary of student names and grades for HW4

Midterm_dict = {fullname[i]: MidtermGrades[i] for i in range(len(fullname))} # produces dictionary of student names and grades for Midterm
Midterms = pd.Series(Midterm_dict) # produces series from dictionary of student names and grades for Midterm

Final_dict = {fullname[i]: FinalGrades[i] for i in range(len(fullname))} # produces dictionary of student names and grades for Final
Finals = pd.Series(Final_dict) # produces series from dictionary of student names and grades for Final

student_df = pd.DataFrame({'HW 1': HW1,
                           'HW 2': HW2,
                           'HW 3': HW3,
                           'HW 4': HW4,
                           'Midterms': Midterms,
                           'Finals': Finals}) # produces dataframe from the set of series HW1, HW2, HW3, HW4, Midterms, and Finals

student_df # displays dataframe


HW 1  HW 2  HW 3  HW 4  Midterms  Finals
Sandra Heller       91    61    85    97        57      96
James Atkinson      55    89    64    89        70      77
Emma Gifford        63    91    50    91        55      80
Kent Chambers       78    63    84    50        82      89
Janet Gaden         64    55    64    51        87      78
Edgar Girdley       58    89    55    89        66      84
Taylor Busi         86    56    80    91        68      69
Patricia Garrick    66    88    63    66        66      63
Christine Dyer      75    76    53    96       100      78
Maria Almaraz       97    50    70    70        59      86

In [ ]:
student_df.to_csv('student_df.csv') # saves dataframe as CSV

[BONUS QUESTION] <b>Question 3(a):</b> [<span style="color: red;">10 points</span>]: From the dataframe <code>student_df</code>, calculate and display the average (mean) score for each student (i.e for each row) and for each categories (i.e for each column). Create <code>student_df2</code>  by copying <code>student_df</code>. In <code>student_df2</code> add a column called Average that contains the average score of all students. Finally, sort by value for the Average column.

In [ ]:
#Your answers go here
student_df.mean(1) # finds the average grade of each student

Sandra Heller       81.166667
James Atkinson      74.000000
Emma Gifford        71.666667
Kent Chambers       74.333333
Janet Gaden         66.500000
Edgar Girdley       73.500000
Taylor Busi         75.000000
Patricia Garrick    68.666667
Christine Dyer      79.666667
Maria Almaraz       72.000000
dtype: float64

In [ ]:
student_df.mean() # finds the average grade of each assignment

HW 1        73.3
HW 2        71.8
HW 3        66.8
HW 4        79.0
Midterms    71.0
Finals      80.0
dtype: float64

In [ ]:
student_df2 = student_df.copy() # produces a copy of the student_df dataframe stored in student_df2
student_df2['Average'] = pd.Series(student_df.mean(1)) # produces a new column in student_df2 derived from the average scores of each student
student_df2.sort_values(by='Average', axis=0) # arranges the data frame by the average column

HW 1  HW 2  HW 3  HW 4  Midterms  Finals    Average
Janet Gaden         64    55    64    51        87      78  66.500000
Patricia Garrick    66    88    63    66        66      63  68.666667
Emma Gifford        63    91    50    91        55      80  71.666667
Maria Almaraz       97    50    70    70        59      86  72.000000
Edgar Girdley       58    89    55    89        66      84  73.500000
James Atkinson      55    89    64    89        70      77  74.000000
Kent Chambers       78    63    84    50        82      89  74.333333
Taylor Busi         86    56    80    91        68      69  75.000000
Christine Dyer      75    76    53    96       100      78  79.666667
Sandra Heller       91    61    85    97        57      96  81.166667